spring:
  application:
    name: consumer-movie
server:
  port: 7902
user: 
  userServicePath: http://localhost:7901/
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
